export const AppRoutes = {
  Home: "/",
  About: "/about",
  WarcraftBuildOrder: "/warcraft/build-order/:id",
  WarcraftBuildOrders: "/warcraft",
  StarcraftBuildOrder: "/starcraft/build-order/:id",
  StarcraftBuildOrders: "/starcraft",
  StormgateBuildOrder: "/stormgate/build-order/:id",
  StormgateBuildOrders: "/stormgate",
  BuildOrders: "/build-orders",
  UserProfile: "/user-profile",
  WarcraftCreate: "/warcraft/create",
  StarcraftCreate: "/starcraft/create",
  StormgateCreate: "/stormgate/create",
};
